github_ssh_key: ENC[AES256_GCM,data:3GlViewud/UllbgUrGsQNOgxoczhaeagZvy1znz2FHg2IWwQwJYzkYBAfLtIL1wjPA4tbdiiPfOoWQivnUJ+7gUJZCu0z/e04qIrKN+WA2UGOHVpyD0XjuOcaTGt4Iz3XD57KOB/9tWQ9j7IwLKkeOqCdz6esx/9YYeUcCMAUlDaYBACI/k4ns0ODT5H/anqSEtcuG7zVsfCI0eR+WglqDj3g9S/37dd59IgP0sbRF90Vi9vAbLTc4qaHDykcXefLZewqJp+bwkT2vPo4dakO9WaekTqQy3t9vBdqHt54mWNzxYOIbj5vxXzO4w8bUstuBUZL+hhcsjOvWITqteFb+nL0h0oT+1dGDqtf1Oxx9+bDTXHcLd2+yFneqr5AsFsKAdul/Yl9Fhvxv2jr26/dH0L50n61N7tIQT5lphdzTKNSxpBQUsCt2Woco0JeVnDf1pNLYTbOpcHFJjtlpojLKYwIw6vn1zMbSsPOCzJr+3dpAbHIPR1NVPwlbmN5h8odQZTHPPON10cCFMAJSXDlW+PK+6vKnM72vhl,iv:KwXRXoki8d926pmuWaF2pbT5EEHrrqVGmXzm+43kyxE=,tag:jflrSqIy1R0vwiDOqgdHeA==,type:str]
sops:
    age:
        - recipient: age1alpaa4ru3ezvtq4mnqyxrd2347tdec5tnyzu32yp7sc9pr03rquq57jsuq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc0NXdlhnN3Z0WVZ6RkhH
            OGx5eXhWOVhWcm1GSnQ3ZkowMVBwU0RKVXdnCnVOVlJTV1RUZEh5dWpKRlgrd0x6
            cjB2SXlHbDNZZWZFQTdEV3ZpQlQ0Z0kKLS0tIGRob2M0YjIxRlJlY0hCcXBtZHlQ
            bFd1ZTBpU2dMRDg2S0NkZEVpWXZLZE0KLmeK2SganszTikiVVsBPeuRlH/tgHjl2
            y1h4yisRb7iXkiHRPcd0OhtciCAXSFPkQhq6CtplSfHzzNiz5Lzihg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T09:39:04Z"
    mac: ENC[AES256_GCM,data:L1CvCWOqvNG31syXibYxkAhsbjZkZMyklWKJhZ2QHebA0UPsy+ckW1o/HqYhqs9mOsdO82tyOyEgYkFSGE8G57Nx4sLZGG19AGUH6R9LgxwlrxP8mqZm0DEvRMnTW/ME4OMLXo15QT5ZZ9r5rfRkf6kOtUC/3NfoGXEGORA8aok=,iv:NqF4ezQ0PbC17T8fdIkE7D9NLMT/oEv6PrwbxU0m7uc=,tag:d7Mtso7xVfF0xTBqYrEyWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
